[user]
	email = jonne.pihlanen@sleek.works
	name = Jonne Pihlanen
[pull]
	rebase = true
[rebase]
	autoStash = true
[merge]
	conflictstyle = "diff3"
[core]
	editor = "nvim"
[init]
	defaultBranch = "main"
[push]
	autoSetupRemote = true
    recurseSubmodules = "check"
[diff]
	submodule = "log"
[status]
    submodulesummary = true
[submodule]
    recurse = true
[safe]
	directory = /opt/flutter
