[user]
	email = jonne.pihlanen@sleek.works
	name = Jonne Pihlanen
[pull]
	rebase = true
[rebase]
	autoStash = true
[merge]
	conflictstyle = "diff3"
[core]
	editor = "nvim"
[init]
	defaultBranch = "main"
[push]
	autoSetupRemote = true
[diff]
	submodule = log
