#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# layout
yabai -m config layout bsp

yabai -m config window_placement second_child

# padding
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# mouse settings
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
# left click + drag
yabai -m config    mouse_action1 move
# right click + drag
yabai -m config    mouse_action2 resize
yabai -m config   mouse_drop_action swap

# disable some apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Xcode$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Google Chrome$" manage=off

# hibe menubar
# yabai -m config menubar_opacity 0.0

echo "yabai configuration loaded.."
